// <auto-generated />
using DomainDefinitions.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoreApplication.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231228163602_Initial Migration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DomainDefinitions.Models.BookData", b =>
                {
                    b.Property<long>("DateTimeUnixMS")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<decimal>("AskPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("AskSize")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("BidPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("BidSize")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("CryptoPair")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("DateTimeUnixMS");

                    b.ToTable("bookDatas");
                });

            modelBuilder.Entity("DomainDefinitions.Models.Subscription", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CryptoPair")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("FrequencyMS")
                        .HasColumnType("int");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
